[package]
name = "sdk"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
contract = ["schema", "storage"]
schema = ["dep:cosmwasm-schema"]
storage = ["dep:cosmwasm-storage", "dep:cw-storage-plus"]
testing = [
    "dep:cw-multi-test",
    "dep:cosmwasm-schema",
    "dep:serde",
    "dep:anyhow",
    "cosmos_ibc",
]
cosmos_ibc = ["cosmos", "cosmwasm-std/ibc3", "dep:cosmos-sdk-proto"]
cosmos = []
neutron = ["cosmwasm-std/stargate", "dep:neutron-sdk"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true, optional = true }
cosmwasm-schema = { workspace = true, optional = true }
cw-storage-plus = { workspace = true, optional = true }
cosmos-sdk-proto = { workspace = true, optional = true }
neutron-sdk = { git = "https://github.com/neutron-org/neutron-contracts", workspace = true, optional = true }

serde = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
