[package]
name = "versioning"
version = "0.0.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdk = { workspace = true, features = ["cosmos", "storage"] }

serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1"
