name: "Check features"

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: "always"
  # Release version is set to `ci` to allow building during checking and testing
  # pipelines, which is ignored during optimized builds.
  RELEASE_VERSION: "ci"
  # Network's name is set to `main` to allow building during checking and testing
  # pipelines, which is ignored during optimized builds.
  NET_NAME: "main"
  # DEX name to check with
  DEX: "osmosis"

jobs:
  check_features_debug:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/check_features@main"
        with:
          profile: "dev"
  check_features_test_debug:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/check_features@main"
        with:
          profile: "test"
          debug_assertions: "true"
  check_features_test_release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/check_features@main"
        with:
          profile: "test"
          debug_assertions: "false"
  check_features_release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/check_features@main"
        with:
          profile: "release"
